### ISSUE TITLE
Suggestions: Add some infos in Readme 

### ISSUE THREAD

**Issue by codeclash** [CESARDELATORRE/TensorFlowImageClassificationWebApp#1]
1. When running/debugging the app from Visual Studio, the server port might be a random port: One must adapt that port (and maybe even switch to http instead of https) in [upload.js](https://github.com/CESARDELATORRE/TensorFlowImageClassificationWebApp/blob/master/WebAppUsingInMemoryImages/WebApp/wwwroot/js/upload.js#L1)

2. I trained a **multiclass multilabel model** in [https://www.customvision.ai](https://www.customvision.ai) and downloaded the tensorflow model. Upon testing with my images, I noticed (after correcting the width/height with [https://lutzroeder.github.io/netron/](https://lutzroeder.github.io/netron/) according to [your article](https://devblogs.microsoft.com/cesardelatorre/run-with-ml-net-c-code-a-tensorflow-model-exported-from-azure-cognitive-services-custom-vision/), I got predictions, but all with very low score for each class. I think it was due to the image offset:
After setting `mean = 0` [here](https://github.com/CESARDELATORRE/TensorFlowImageClassificationWebApp/blob/master/WebAppUsingInMemoryImages/WebApp/ML/TensorFlowModelConfigurator.cs#L28) it worked like expected.

Thx for providing this nice and tidy sample btw!

**Comment by CESARDELATORRE** [comment]
Have you tried the final version which is public at the official samples repo?
Here:
https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/end-to-end-apps/DeepLearning_ImageClassification_TensorFlow 
I think that one shouldn't have the port issue?

**Comment by bamurtaugh** [comment]
Hi @codeclash - we have updated the [official sample's readme](https://github.com/dotnet/machinelearning-samples/tree/master/samples/csharp/end-to-end-apps/DeepLearning_ImageClassification_TensorFlow) about the need to potentially change image settings when using a custom Tensor Flow model. Thanks for the feedback!

**Comment by codeclash** [comment]
Just looked at it now that I saw the link. Yep using a relative url in js for the fetch is actually simpler 👍

**Comment by codeclash** [comment]
@bamurtaugh that was fast 👌

**Comment by bamurtaugh** [comment]
@codeclash We are doing our best to monitor issues and update our samples repo to best help the community 😄 Feel free to provide us any other feedback in our repo!

**Comment by CESARDELATORRE** [comment]
Closing this issue. 👍
